name: Update readme with blog posts
on: 
  schedule:
    # Update everyday at 12 AM
    - cron: 0 0 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://www.waleedmumtaz.com/blog/rss.xml'
          file: 'README.md'
      - uses: sarisia/actions-commit@master
